services:
  rocketpy:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: rocketgnc-dev
    restart: unless-stopped

    working_dir: /app

    volumes:
      - .:/app

    stdin_open: true
    tty: true

    command: python